site_name: "ensure-cuda"
site_url: https://ericmjl.github.io/ensure-cuda

docs_dir: docs/

# For more configuration on the theme, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  icon:
    logo: "fontawesome/solid/book"
  features:
    - instant
    - tabs
  language: en

# We customize the navigation by hand to control the order
# in which pages show up.

plugins:
  - search
# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - markdown.extensions.attr_list

extra_css:
  - apidocs.css

extra_javascript:
  - config.js

repo_name: "ericmjl/ensure-cuda"
repo_url: "https://github.com/ericmjl/ensure-cuda"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/ericmjl"
